### ISSUE TITLE
Hypixal Cry Mod Not Working

### ISSUE THREAD

**Issue by eatapplesdummy** [Nekiplay/Hypixel-Cry#5]
i was trying this out and nothing is happening like i tried touching stuff but nothing was happening i dont think its working im using 1.8.9 forge im just using this mod dulkirmod- and Scrollable Tooltips-1.4 (1.8.9) 

the only think working is the treasure esp no nuke is working

**Comment by eatapplesdummy** [comment]
is there a keybind to start the nuke or something please help

**Comment by eatapplesdummy** [comment]
what are the keybinds for the nukes

**Comment by Nekiplay** [comment]
need OneConfig and Essential mod

**Comment by eatapplesdummy** [comment]
then what

**Comment by eatapplesdummy** [comment]
make a video please

**Comment by eatapplesdummy** [comment]
![image pngeeee](https://github.com/Nekiplay/Hypixel-Cry/assets/146778544/ae05b135-a576-48d1-9f17-4f92168f3648)

this is what happens when i do /cry

**Comment by Nekiplay** [comment]
keybinds in minecraft binds menu

**Comment by eatapplesdummy** [comment]
got banned ;(
